# This is a basic workflow to help you get started with Actions

name: Deploy do projecto api

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [ main ]

        # Allows you to run this workflow manually from the Actions tab
        workflow_dispatch:

        # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        name: Deploy
        runs-on: ubuntu-latest
        steps:
          - name: Deploying project on testing enviroment
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.TEST_HOSTNAME }}
                username: ${{ secrets.TEST_USERNAME }}
                password: ${{ secrets.TEST_PASSWORD }}
                port: ${{ secrets.TEST_PORT }}
                script: cd /var/nc_projects/api-faturacao/ && sudo -S <<< "${{ secrets.TEST_PASSWORD }}" git pull https://ncsoftwarehouse:${{ secrets.DEPLOY_KEY }}@github.com/NC-SOFTWARE-HOUSE/api-faturacao.git main && sudo -S <<< "${{ secrets.TEST_PASSWORD }}" bash deploy.sh